crud/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("polls.urls"), name="index"),
    path("admin/", admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

polls/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views


app_name = "polls"
urlpatterns = [
    path("", views.index2, name="index"),
    path("<int:question_id>", views.edit2, name="edit"),
    path("<int:question_id>/delete", views.delete2, name="delete"),
]

polls/models.py
import datetime

from django.contrib import admin
from django.db import models
from django.utils import timezone


class Product(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


# class Choice(models.Model):
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     choice_text = models.CharField(max_length=200)
#     votes = models.IntegerField(default=0)

#     def __str__(self):
#         return self.choice_text

polls/forms.py
import re

from django import forms


class CreateForm(forms.Form):
    question_text = forms.CharField(
        max_length=200,
        error_messages={"required": "El campo no puede estar vacío."},
    )

    def clean_question_text(self):
        question_text = self.cleaned_data.get("question_text")
        validate_question_text(question_text)
        return question_text


class UpdateForm(forms.Form):
    question_id = forms.IntegerField()
    question_text = forms.CharField(
        max_length=200,
        error_messages={"required": "El campo no puede estar vacío."},
    )

    def clean_question_text(self):
        question_text = self.cleaned_data.get("question_text")
        validate_question_text(question_text)
        return question_text
    
    def clean(self):
        cleaned_data = super().clean()
        question_id = cleaned_data.get("question_id")
        try:
            question_id = int(question_id)
        except Exception as e:
            print(f"[CrudForm] -> clean - Error: {e}")
            raise forms.ValidationError("Error inesperado.")
        
        return cleaned_data


class DeleteForm(forms.Form):
    question_id = forms.IntegerField()
    
    def clean_question_id(self):
        question_id = self.cleaned_data.get("question_id")
        try:
            question_id = int(question_id)
        except Exception as e:
            print(f"[CrudForm] -> clean - Error: {e}")
            raise forms.ValidationError("Error inesperado.")
        
        return question_id


def validate_question_text(question_text) -> None:
    if not question_text:
        raise forms.ValidationError("El campo no puede estar vacío.")

    if not re.match(r'^[a-zA-Z0-9\s]+$', question_text):
        raise forms.ValidationError("Solo se puede ingresar letras y espacios")

polls/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils import timezone

from crud.database2 import execute_query
from polls.forms import CreateForm, UpdateForm, DeleteForm


def index(request):

    if request.method == "POST":
        form = CreateForm(request.POST)
        today = timezone.now()
        if form.is_valid():
            question_text = form.cleaned_data["question_text"]
            query = "INSERT INTO polls_product (question_text, pub_date) VALUES (%s, %s)"
            execute_query(query, (question_text, today))
            messages.success(request, "Registro creado.")
        else:
            messages.error(request, "Hubo un error en el formulario.")
    else:
        form = CreateForm()

    query = "SELECT * FROM polls_product ORDER BY pub_date DESC LIMIT 5"
    latest_question_list = execute_query(query, fetch=True)
    context = {
        "form": form,
        "latest_question_list": latest_question_list,
    }
    return render(request, "polls/index.html", context)


def edit(request, question_id):
    query = "SELECT * FROM polls_product WHERE id = %s"
    question = execute_query(query, (question_id,), fetch=True)

    if not question:
        messages.error(request, "El registro no existe.")
        return redirect(reverse("polls:index"))

    question = question[0]

    if request.method == "POST":
        form = UpdateForm(request.POST)
        if form.is_valid():
            question_text = form.cleaned_data.get("question_text")
            query = "UPDATE polls_product SET question_text = %s WHERE id = %s"
            execute_query(query, (question_text, question_id))
            messages.success(request, "Registro actualizado.")
            return redirect(reverse("polls:index"))
        else:
            messages.error(request, "Error al editar el registro.")
    else:
        form = UpdateForm(initial={"question_text": question["question_text"]})

    return render(
        request,
        "polls/detail.html",
        {
            "form": form,
            "question": question
        },
    )


def delete(request, question_id):
    query = "SELECT * FROM polls_product WHERE id = %s"
    question = execute_query(query, (question_id,), fetch=True)
    if not question:
        messages.error(request, "El registro que se intentó borrar no existe.")
        return redirect(reverse("polls:index"))

    question = question[0]
    if request.method == "POST":
        try:
            q_id = int(request.POST.get("question_id", None))
        except Exception:
            messages.error(request, "Hubo un error inesperado. Intenta de nuevo.")
            return redirect(reverse("index"))

        if question_id != q_id:
            messages.error(request, "Hubo un error inesperado. Intenta de nuevo.")
            return redirect(reverse("index"))

        question_text = question["question_text"]
        query = "DELETE FROM polls_product WHERE id = %s"
        execute_query(query, (question_id,))
        messages.success(request, "El registro '%s' fue eliminado" % question_text)
        return redirect(reverse("polls:index"))

    elif request.method == "GET":
        return render(
            request,
            "polls/delete.html",
            {"question": question}
        )


def index2(request):
    form = CreateForm()

    if request.method == "POST":
        today = timezone.now()
        form = CreateForm(request.POST)

        if not form.is_valid():
            messages.error(request, "No se pudo crear el registro.")
            return redirect(reverse("polls:index"))

        question_text = form.cleaned_data.get("question_text")
        query = "INSERT INTO polls_product (question_text, pub_date) VALUES (%s, %s)"
        success, result = execute_query(query, (question_text,))
        if not success:
            messages.error(request, "No se pudo crear el registro.")
            return redirect(reverse("polls:index"))

        messages.success(request, f"Se creó el registro '{question_text}'.")
        return redirect(reverse("polls:index"))

    query = "SELECT * FROM polls_product ORDER BY pub_date DESC"
    success, questions = execute_query(query, fetch=True)

    return render(
        request,
        "polls/index.html",
        {
            "latest_question_list": questions,
            "form": form,
        }
    )


def edit2(request, question_id):
    if request.method == "POST":
        form = UpdateForm(request.POST)
        if form.is_valid():
            question_text = form.cleaned_data.get("question_text", "")
            question_id_cleaned = form.cleaned_data.get("question_id", None)
            if not question_id or (question_id != question_id_cleaned):
                messages.error(request, "Error al editar el registro.")
                return redirect(reverse("polls:index"))

            query = "UPDATE polls_product SET question_text = %s WHERE id = %s"
            success, result = execute_query(query, (question_text, question_id))
            messages.success(request, "El registro se editó correctamente.")
        else:
            messages.error(request, "Error al editar el registro.")

        return redirect(reverse("polls:index"))
    else:
        form = UpdateForm()

    query = "SELECT * FROM polls_product WHERE id = %s"
    success, question = execute_query(query, (question_id,), fetch=True)
    question = question[0]

    return render(
        request,
        "polls/detail.html",
        {
            "question": question,
            "form": form,
        }
    )


def delete2(request, question_id):
    form = DeleteForm()

    if request.method == "POST":
        form = DeleteForm(request.POST)
        if not form.is_valid():
            print(f"[delete2] -> CrudForm - Error: {form.errors}")
            messages.error(request, "El registro no pudo borrarse.")
            return redirect(reverse("polls:index"))

        question_id_form = form.cleaned_data.get("question_id")
        if question_id_form != question_id:
            messages.error(request, "Error al editar el registro.")
            return redirect(reverse("polls:index"))

        query = "DELETE FROM polls_product WHERE id = %s"
        success, result = execute_query(query, (question_id,))
        if not success:
            print(f"Error: {result}")
            messages.error(request, "El registro no pudo borrarse.")
            return redirect(reverse("polls:index"))

        messages.success(request, "El registro se borró correctamente.")
        return redirect(reverse("polls:index"))

    query = "SELECT * FROM polls_product WHERE id = %s"
    success, question = execute_query(query, (question_id,), fetch=True)
    if not success or len(question) == 0:
        messages.error(request, "El registro que intentas borrar no existe.")
        return redirect(reverse("polls:index"))

    question = question[0]

    return render(
        request,
        "polls/delete.html",
        {
            "question": question,
            "form": form,
        }
    )

templates/polls/delete.html
{% extends "base.html" %}

{% block title_section %}
Eliminar
{% endblock %}

{% block content %}
<p>¿Queres eliminar el registro <strong>{{ question.question_text }}</strong>?</p>

<form method="post">
    {% csrf_token %}
    <input type="hidden" name="question_id" value="{{ question.id }}">
    <input type="submit" value="Si" class="btn btn-link">
    <a href="{% url 'polls:index' %}" class="btn btn-primary">No</a>
</form>
{% endblock %}

templates/polls/detail.html
{% extends "base.html" %}

{% block title_section %}
Editar
{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <label for="question_text">Nombre</label><br>
    <input type="text" value="{{ question.question_text }}" name="question_text"><br>
    <input type="hidden" value="{{ question.id }}" name="question_id">
    {% if form.question_text.errors %}
    {% for error in form.question_text.errors %}<strong>{{ error }}</strong>{% endfor %}
    <br>
    {% endif %}
    <br>
    <input type="submit" value="Editar">
</form>

<br>
<a href="{% url 'polls:index' %}">Volver</a>
{% endblock %}

templates/polls/index.html
{% extends "base.html" %}

{% block title_section %}
Registros
{% endblock %}

{% block content %}
<form action="{% url 'polls:index' %}" method="post">
    {% csrf_token %}
    <label for="question_text">Nombre</label><br>
    <input type="text" name="question_text"><br>
    {% if form.question_text.errors %}
    <span style="color: #dc3545;">{% for error in form.question_text.errors %}<strong>{{ error }}</strong>{% endfor %}</span>
    <br>
    {% endif %}
    <br>
    <input type="submit" value="Registrar">
</form>

<br>
<h2>Lista de registros creados</h2>
{% if latest_question_list %}
<div class="table-responsive small">
    <table class="table table-striped table-sm">
        <thead>
            <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">Fecha creación</th>
            <th scope="col">Fecha edición</th>
            <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for question in latest_question_list %}
            <tr>
                <td>{{ question.id }}</td>
                <td><a href="{% url 'polls:edit' question.id %}">{{ question.question_text }}</a></td>
                <td>{{ question.pub_date }}</td>
                <td>{{ question.updated_date }}</td>
                <td><a href="{% url 'polls:delete' question.id %}">Eliminar</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
    <p>Aún no hay registros creados.</p>
{% endif %}
{% endblock %}

templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:edit' question.id %}">Vote again?</a>